AWSTemplateFormatVersion: '2010-09-09'
# *** Change this to something useful for you!
Description: github-codepipeline-app

# This is just here as an example resource

Resources:
  ApplicationBucket:
    Type: AWS::S3::Bucket

  ExtractApiKeyValue:
    Type: AWS::Lambda::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs12.x
      Timeout: 30
      Code:
        ZipFile: |
          const AWS = require('aws-sdk')
          exports.handler = function (event, context) {
            print(event);
          }