AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
# *** Change this to something useful for you!
Description: github-codepipeline-app

# This is just here as an example resource

Resources:
  ApplicationBucket:
    Type: AWS::S3::Bucket

  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole

  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: LambdaFunction
      Role: !GetAtt LambdaRole.Arn
      Runtime: python3.7
      Handler: index.my_handler
      Code:
        ZipFile: |
          def my_handler(event, context):
            message = 'Hello Lambda World!'
            return message
  
  S3UpdateListener:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: python3.6
      InlineCode: |
        def handler(event, context):
          print("Hello, world!")
          print(event)
      Policies:
        - AWSLambdaExecute
      Events:
        S3Update:
          Type: S3
          Properties:
            Bucket: !Ref DemoBucket
            Events: s3:ObjectCreated:*
  
  DemoBucket:
    Type: AWS::S3::Bucket